---
# tasks file for postgres monitoring
- name: Create directories for prometheus
  file:
    path: /tmp/postgres_exporter
    state: directory
- name: Download postgres exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/postgres_exporter/releases/download/v{{version}}/postgres_exporter-{{version}}.linux-amd64.tar.gz
    dest: /tmp/postgres_exporter
    force: no

- name: Download And Unzipped postgres exporter
  unarchive:
    src: /tmp/postgres_exporter/postgres_exporter-{{version}}.linux-amd64.tar.gz
    dest: /tmp/postgres_exporter
    remote_src: yes
    creates: /tmp/postgres_exporter/postgres_exporter-{{ version }}.linux-amd64

- name: Copy Bin Files From Unzipped to Node exporter
  copy:
    src: /tmp/postgres_exporter/postgres_exporter-{{ version }}.linux-amd64/postgres_exporter
    dest: /usr/local/bin/
    remote_src: yes
    owner: postgres
    group: postgres
    mode: a+x



- name: Create File for Postgres exporter Systemd
  copy:
    src: postgres_exporter.service
    dest: /etc/systemd/system/
  notify:
    - systemd reload