- hosts: etcd
  become: True
  roles:
    - etcd
- hosts: dbs
  become: True
  roles:
    - postgresql
    - patroni
- hosts: dbproxy
  become: True
  roles:
    - haproxy
    - pgbouncer
    - yandex.tank

