- hosts: etcd
  become: True
  roles:
    - etcd
- hosts: dbs
  become: True
  roles:
    - postgresql
    - patroni
    - postgres_monitoring
- hosts: dbproxy
  become: True
  roles:
    - haproxy
    - pgbouncer
    - yandex.tank
    - backend
    - monitoring

