---
# handlers file for etcd
- name: stop service
  systemd:
    name: etcd
    state: stopped
- name: drop cluster
  file:
    path: /var/lib/etcd/default.etcd
    state: absent
- name: restart etcd
  systemd:
    name: etcd
    state: restarted
- name: daemon reload
  systemd:
    name: etcd
    state: reloaded