all:
  children:
    dbs:
    dbproxies:

etcd:
  children:
    dbs:
    dbproxies:


dbproxies:
  hosts:
    dbproxy:
      ip: 10.129.0.18
      ansible_host: 62.84.120.253
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

dbs:
  hosts:
    db1:
      ip: 10.129.0.25
      ansible_host: 158.160.8.153
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    db2:
      ip: 192.168.10.7
      ansible_host: 127.0.0.1
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa