all:
  children:
    dbs:
    dbproxies:

etcd:
  children:
    dbs:
    dbproxies:


dbproxies:
  hosts:
    dbproxy:
      ip: 10.129.0.36
      initial_cluster_state: "new"
      ansible_host: 130.193.54.223
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

dbs:
  hosts:
    db1:
      ip: 10.129.0.25
      initial_cluster_state: "new"
      ansible_host: 130.193.54.39
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    db2:
      ip: 10.129.0.6
      initial_cluster_state: "new"
      ansible_host: 130.193.55.135
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa